name: ${project.name}
main: jp.azisaba.main.survival.AzisabaSurvival
version: ${project.version}
author: AzisabaDev
description: ${project.description}
website: ${project.url}
api-version: 1.13
softdepend: ["Vault", "Essentials", "mcMMO", "Votifier"]
commands:
  azisabasurvival:
    usage: "/{LABEL} reload"
    permission: azisabasurvival.command.azisabasurvival
    aliases: ["as"]
  vote:
    usage: "/vote"
    permission: azisabasurvival.command.vote
permissions:
  azisabasurvival.command.azisabasurvival:
    default: op
  azisabasurvival.earnmoney:
    default: true
  azisabasurvival.command.vote:
    default: true
  azisabasurvival.command.vote.give:
    default: op
  azisabasurvival.moneyfly.create:
    default: op
  azisabasurvival.moneyfly.buy:
    default: true